# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 501)
        MainWindow.setStyleSheet("QWidget {\n"
"    font: 8pt \"Calibri\";\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"    background-image: url(bg.jpg);\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 25pt \"Calibri\";\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: qlineargradient(spread:pad,\n"
"    x1: 0.29,\n"
"    y1: 0.471909,\n"
"    x2: 0.931818,\n"
"    y2: 0.227,\n"
"    stop: 0 rgba(109, 0, 180, 255),\n"
"    stop: 1 rgba(41, 147, 255, 255));\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(0, 210, 233);\n"
"    box-sizing: border-box;\n"
"    color: #FFFFFF;\n"
"    cursor: pointer;\n"
"    font-size: 30px;\n"
"    font-weight: 500;\n"
"    text-align: center;\n"
"    transition: all .5s;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #000;\n"
"    border-style: inset;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: qlineargradient(spread:pad,\n"
"    x1: 0.29,\n"
"    y1: 0.471909,\n"
"    x2: 0.931818,\n"
"    y2: 0.227,\n"
"    stop: 0 rgba(109, 0, 180, 255),\n"
"    stop: 1 rgba(41, 147, 255, 255));\n"
"    border-radius: 8px;\n"
"    box-sizing: border-box;\n"
"    color: #FFFFFF;\n"
"    cursor: pointer;\n"
"    font-size: 30px;\n"
"    font-weight: 500;\n"
"    text-align: center;\n"
"    transition: all .5s;\n"
"    border: 3px solid rgb(0, 210, 233);\n"
"}\n"
"\n"
"\n"
"QComboBox:editable {\n"
"    background-color: qlineargradient(spread:pad,\n"
"    x1: 0.29,\n"
"    y1: 0.471909,\n"
"    x2: 0.931818,\n"
"    y2: 0.227,\n"
"    stop: 0 rgba(109, 0, 180, 255),\n"
"    stop: 1 rgba(41, 147, 255, 255));\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background-color: qlineargradient(spread:pad,\n"
"    x1: 0.29,\n"
"    y1: 0.471909,\n"
"    x2: 0.931818,\n"
"    y2: 0.227,\n"
"    stop: 0 rgba(109, 0, 180, 255),\n"
"    stop: 1 rgba(41, 147, 255, 255));\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background-color: qlineargradient(spread:pad,\n"
"    x1: 0.29,\n"
"    y1: 0.471909,\n"
"    x2: 0.931818,\n"
"    y2: 0.227,\n"
"    stop: 0 rgba(109, 0, 180, 255),\n"
"    stop: 1 rgba(41, 147, 255, 255));\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 5px;\n"
"    font-family: Arial;\n"
"    font-size: 18pt;\n"
"    border: none;\n"
"    outline: none;\n"
"    text-align: center;\n"
"    border-bottom: 5px solid qlineargradient(spread:pad,\n"
"    x1: 0.29,\n"
"    y1: 0.471909,\n"
"    x2: 0.931818,\n"
"    y2: 0.227,\n"
"    stop: 0 rgba(109, 0, 180, 255),\n"
"    stop: 1 rgba(41, 147, 255, 255));\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"\n"
"QComboBox:select {\n"
"    background-color: qlineargradient(spread:pad,\n"
"    x1: 0.29,\n"
"    y1: 0.471909,\n"
"    x2: 0.931818,\n"
"    y2: 0.227,\n"
"    stop: 0 rgba(109, 0, 180, 255),\n"
"    stop: 1 rgba(41, 147, 255, 255));\n"
"    border-style: inset;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget.setGeometry(QtCore.QRect(50, 400, 610, 101))
        self.horizontalWidget.setStyleSheet("")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(1, 0, 5, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalWidget)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("  border-radius: 0px; padding-top:1.7;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_2.setEnabled(True)
        self.horizontalWidget_2.setGeometry(QtCore.QRect(50, 70, 601, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy)
        self.horizontalWidget_2.setStyleSheet("QPushButton {padding:30px;font-size: 45px;}")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(100)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 250, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(510, 10, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 191, 71))
        self.comboBox.setStyleSheet("")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(1, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 310, 601, 101))
        self.frame.setStyleSheet("background-image: url(img.png);border: 3px solid rgb(0, 210, 233);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Принтер этикеток"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Введите MAC адрес"))
        self.pushButton_4.setText(_translate("MainWindow", "MAC"))
        self.pushButton.setText(_translate("MainWindow", "ПЕЧАТЬ"))
        self.pushButton_2.setText(_translate("MainWindow", "ТЕСТ"))
        self.pushButton_3.setText(_translate("MainWindow", "Поменять длину"))
        self.pushButton_6.setText(_translate("MainWindow", "Помощь"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Выбор COM"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Выбор COM"))
